### ISSUE TITLE
Makei Build Error: Cannot decomposite filename: OPM.CLP

### ISSUE THREAD

**Issue by kraudy** [IBM/bob-recursive-example#12]
Hi, i was trying to follow the bob getting-started on PUB400 but i get this error with `makei build`

Any idea?

![image](https://github.com/IBM/bob-recursive-example/assets/19917977/f75aee9a-b579-4af6-b08f-9fcd0d05ae27)

**Comment by kraudy** [comment]
Tried changing OPM.CLP to OPM.CLLE and Rules.mk from OPM.CLP to OPM.PGM.CLLE

Now i get this error

![image](https://github.com/IBM/bob-recursive-example/assets/19917977/ce339d23-cd81-4639-b25a-5e49b185a6eb)

**Comment by kraudy** [comment]
maybe @edmundreinhardt  or @worksofliam  can give me a hand

**Comment by kraudy** [comment]
Well, i almost got it to work deleting these directories and removing them from the ./Rules.mk QBNDSRC QCBLSRC QCLSRC QCMDSRC QDTASRC

![image](https://github.com/IBM/bob-recursive-example/assets/19917977/feff57b2-01c1-4505-9ab1-a17fc30feef4)

Not something im proud of

**Comment by edmundreinhardt** [comment]
OK we FINALLY have released 2.4.27 which will fix this.
Note you may have to upgrade your python
Please ReOpen if you still see a problem.
