### ISSUE TITLE
"How to" questions.

### ISSUE THREAD

**Issue by Russ-illumifin** [IBM/bob-recursive-example#18]
I have posted these questions in the Source Orbit repo as well but I'm not 100% clear which project takes care of these questions so I am also posting them here. These questions seem to be more related to BOB.

I am using Source Orbit to run the builds with this command within VSCode: 

> "so -bf --verbose make && /QOpenSys/pkgs/bin/gmake -i LIBL='ANNDEVRR AIMPRODDTA QS36F IDOCS684 ' BIN_LIB=&CURLIB OPT=*EVENTF"

1. I have 11 commands to create and none of them get created. The commands don't attempt to create (at least they don't show up in the build output). The Rules.mk file has the command names and the command processing program (CPP) names used when the command is created. I have 3 commands in this Rules.mk file for testing. How do I create the commands?
```
ANMAST01CL.CMD: anmast01cl.cmd ANMAST01CL.PGM 
ANMAST01CL.CMD: PGM=ANMAST01CL
ENDJOBLCK.CMD: endjoblck.cmd ENDJOBLCK.PGM
ENDJOBLOG.CMD: PGM=ENDJOBLCK
SNDFILE.CMD: sndfile.cmd SNDFILE.PGM
SNDFILE.CMD: PGM=SNDFILE
``` 

2.  Using the bob-recursive example, I created two files to create two binding directories. These do not get created. I created a .BNDDIR file with the commands to run to create the binding directory along with the Rules.mk file. Can I create my own binding directories?

```
/* Need to delete the BNDDIR, or it will always be older than the source */
/* because the CRTBNDDIR will fail the second time and only the ADDBNDDIRE is executed */     
!DLTOBJ OBJ(&O/&N) OBJTYPE(*BNDDIR)
CRTBNDDIR BNDDIR(&O/&N)
ADDBNDDIRE BNDDIR(&O/&N) +
   OBJ((PANMAST      *SRVPGM) +
(PANMAST2     *SRVPGM) +
(PSYSTEM      *SRVPGM))
```
3. I found basic information in the documentation about how to override commands (https://ibm.github.io/ibmi-bob/#/prepare-the-project/rules.mk?id=overriding-compile-settings). Is there a way to specify a _global_ override? I was looking for a way to override command parameters such as the OPTION parm on the CRTSQLRPGI command. This is a parm that cannot be modified using the CHGCMDDFT command.

**Comment by Russ-illumifin** [comment]
It doesn't look like it. This is the command I am using with Source Orbit:

> "so -bf --verbose make && /QOpenSys/pkgs/bin/gmake -i LIBL='ANNDEVRR AIMPRODDTA QS36F IDOCS684 ' BIN_LIB=&CURLIB OPT=*EVENTF"

Should I change that from ```gmake``` to ```makei b```? 

Or do you have another suggestion?

There are some ```makei``` commands in the VSCode actions.json also:

```
"name": "Build all",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs",
      ".evfevent"
    ]
-- and --
"name": "Build current",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei compile -f &BASENAME",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs",
      ".evfevent"
    ]
```

**Comment by edmundreinhardt** [comment]
yes change `gmake` to `makei b`

the VSCode action includes `OPT=*EVENTF` in order to get the eventf compiler feedback downloaded.
If you use ibmi-project-explorer this will not be necessary

**Comment by Russ-illumifin** [comment]
I am using the IBM i Project Explorer Extension.

I changed the Source Orbit command to the following:

> so -bf --verbose make && OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei b

I also ran the following command to run only the ```makei``` build:

> OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build

Both of these fail with the following error (INDEX is not a recognized file extension).
```
Commands:
                OPT=*EVENTF BUILDLIB=anndevrr /QOpenSys/pkgs/bin/makei build

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 293, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 41, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 254, in handle_build
    build_env = BuildEnv([target], args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 65, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 85, in _create_build_vars
    rules_mk = RulesMk.from_file(rules_mk_path,  self.src_dir, map(Path, self.iproj_json.include_path))
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 185, in from_file
    rules_mk = RulesMk.from_str(rules_mk_str, rules_mk_path.parent, src_dir, include_dirs)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 270, in from_str
    return RulesMk(subdir, rules, containing_dir)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 151, in __init__
    tgt_group = FILE_TARGETGROUPS_MAPPING[decompose_filename(rule.source_file)[-2]]
  File "/QOpenSys/pkgs/lib/bob/src/makei/utils.py", line 248, in decompose_filename
    raise ValueError(f"Cannot decomposite filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decomposite filename: anbenei1.index as INDEX is not a recognized file extension

Fetching errors from .evfevent.
Failed to download a file after Action: No such file

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

**Comment by Russ-illumifin** [comment]
Here are more details:

I see that INDEX is a valid file extension in the documentation, so I think the file name is valid.
> https://ibm.github.io/ibmi-bob/#/welcome/features?id=support-sql-pseudo-source

Here is content of the anbenei1.index file (the file name is all lowercase):
```
drop index ANBENE_POLICY_NUMBER_0001;

CREATE INDEX ANBENE_POLICY_NUMBER_0001                             
  FOR SYSTEM NAME ANBENEI1 ON ANNFILS.ANBENE                                                     
  ( RIGHT ( '000' || CAST ( ABYEAR# AS VARCHAR ( 3 ) ) , 3 )                                                             
  || RIGHT ( '00' || CAST ( ABMON# AS VARCHAR ( 2 ) ) , 2 )   
  || RIGHT ( '000000' || CAST ( ABSEQ# AS VARCHAR ( 6 ) ) , 6 )       
  AS POLICY_NUMBER FOR COLUMN POLNUM ASC )                                 
  RCDFMT ANBENEI1 ADD ALL COLUMNS;

-- Here is a simpler way to create the same field:
--CREATE INDEX ANBENE_POLICY_NUMBER_0001
--	FOR SYSTEM NAME ANBENEI1 ON ANBENE
--  ( digits( ABYEAR#) || digits ( ABMON#) || digits( ABSEQ#)
--  AS POLICY_NUMBER FOR COLUMN POLNUM ASC )                                 
--  RCDFMT ANBENEI1 ADD ALL COLUMNS;
```
This is how the file is specified in the Rules.mk file:
```
ANBENEI1.FILE: anbenei1.index ANBENE.FILE
```

**Comment by edmundreinhardt** [comment]
I think you have found a valid defect.  I will try to reproduce and confirm.  It looks like you are doing things correctly

**Comment by edmundreinhardt** [comment]
Hi Russ @Russ-illumifin 
I tried and this all worked correctly as indicated by 
![image](https://github.com/user-attachments/assets/38a89ae3-fd8e-432a-904a-9eaf8378db39)

Note:
your `so -bf make` should really be changes to `so -bf bob`

Also note that since you are using the amazing Project Explorer, you can do this through the UI
![Screenshot 2024-11-01 at 9 48 32 AM](https://github.com/user-attachments/assets/837da0fc-0166-4f2c-8207-a9f9a203301a)

And make sure to deploy  so that your Rules.mk gets updated on the IFS when you run

**Comment by edmundreinhardt** [comment]
Also note that I used  `CREATE OR REPLACE INDEX` to avoid the `DROP` which fails in a new library.
Also I did not fully qualify the reference TABLE to allow me to pick it up from other libraries in my dev environment.
