### ISSUE TITLE
Support for QPNLSRC?

### ISSUE THREAD

**Issue by ravisankar-PIO** [IBM/bob-recursive-example#20]
Hi,
     As ancient as it may sound, I want to know if we are supporting the compilation of QPNLSRC source files?

QPNLSRC are the F1-help guide for any screen in IBM i .
**If yes, how do I define them in my rules.mk?**

![image](https://github.com/user-attachments/assets/f8623ea4-5d0a-4037-82da-14fa2dfeeab4)

Please refer to this IBM I page to learn more about QPNLSRC
https://www.bing.com/ck/a?!&&p=668763121402ad071c66b562565ecfd4fca9189b29f6a4cb6347b071a6fa6d83JmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=3adb2872-8161-6cbb-20f6-3b9680966d54&psq=qpnlsrc+in+ibm+i&u=a1aHR0cHM6Ly93d3cuaWJtLmNvbS9kb2NzL2VuL2kvNy40P3RvcGljPXNzd19pYm1faV83NC9jbC9jcnRwbmxncnAuaHRt&ntb=1

Regards,
Ravisankar Pandian.

**Comment by edmundreinhardt** [comment]
You have come to the right place.  Right in this repo under QPNLSRC, you will see how we successfully support PNLGRP source.
https://github.com/IBM/bob-recursive-example/tree/master/QPNLSRC

and this document lists all supported source types https://ibm.github.io/ibmi-bob/#/welcome/features

```Rules.mk
SAMHELP.PNLGRP: SAMHELP-Help_Application_Sam.PNLGRPSRC
```
