### ISSUE TITLE
Code for IBM i Considerations

### ISSUE THREAD

**Issue by SJLennon** [IBM/bob-recursive-example#3]
Learning/testing Bob on PUB400.COM using Code for IBM i.   

Couple of issues.
1) I defined `&LIB1` variable in Code for IBM i. However, Code for IBM i forces it to upper case and in `iproj.json` it is `&lib1`, which means the build immediately fails.  Changing it to upper case in `iproj.json` gets me much further.
2) I had to create a `.logs` directory since there is none in this project.
3) I realize this is a complex project.  Is is supposed to build without errors?  (I have some errors that I suspect are related to CCSID issues, since I have CCSID 37 in my user profile on a machine that is running CCSID 273. I will investigate more.)
@edmundreinhardt

**Comment by edmundreinhardt** [comment]
Liam, is this true that Code for i does not support lower case variables?

**Comment by edmundreinhardt** [comment]
.logs should be created automatically.  No there should not be any errors.  All 153 compile cleanly.
I could force the CCSID to 37 by default to avoid picking up the JOB CCSID.

**Comment by edmundreinhardt** [comment]
Hmm this is already done
<img width="392" alt="image" src="https://user-images.githubusercontent.com/11184579/234976037-55e929a2-bfdc-4860-b7af-b9786ae0d13b.png">

**Comment by edmundreinhardt** [comment]
Please tell me where you are having the trouble.  Maybe some source types are not using TGTCCSID.  Not all compilers support that but we are trying to work around that with our `crtfrmstmf` command.

**Comment by SJLennon** [comment]
I'll delete everything and start all over again with the bob-recursive-example.  Maybe I did something wrong since I'm very new to Bob. Hope to have more feed back tomorrow.

**Comment by worksofliam** [comment]
@edmundreinhardt id have to have a look but I believe so. Perhaps that is an easy fix for us

**Comment by edmundreinhardt** [comment]
I assume this problem has been resolved.  If not, please open an issue on Code for IBM i.

**Comment by edmundreinhardt** [comment]
I should also say there is a vscode-ibmi-projectexplorer extennsion on top of Code for i that works very well
