### ISSUE TITLE
"Odd" characters in QRPGLESRC/XML001 cause compile failure

### ISSUE THREAD

**Issue by SJLennon** [IBM/bob-recursive-example#4]
Windows 10 in the USA.  Displaying source from GITHUB.COM using the Brave browser.

These two lines have "odd" characters which cause the compile to fail.  An easy fix to create a correct comment in my local source.
![image](https://user-images.githubusercontent.com/67484051/234914578-098927de-80ca-44a3-9548-de6c8b68c695.png)

**Comment by edmundreinhardt** [comment]
I see the odd characters and I am fixing them
But I want to point out that my compile succeeds.  I wonder if you are transferring the files to IFS as UTF-8.  This is a requirement for Bob.
The RPG rules are that any char in col 5 is ignored and column 6 is ignored if col 7 is an *
