### ISSUE TITLE
Change objlib for a specific branch

### ISSUE THREAD

**Issue by pabloto** [IBM/bob-recursive-example#8]
Hi,

I'm working in local with visual studio code, I want than the main/master branch contains the production source of my project, so when I have to develop a new function, or correct a bug I want to create a new branch, and my wish is to  compile on a different library on my system bound to this specific branch. My desire is to configure it without change manually the current library.

How can I configure this with bob?

Many thanks.

**Comment by edmundreinhardt** [comment]
I assume that you discoved that by using a variable you can change the target library to whatever makes sense for that context

**Comment by pabloto** [comment]
Hi Bob,

**Comment by edmundreinhardt** [comment]
Hi Pablo, 
In this iproj.json you will see a line specifying  &lib1 as your curlib entry, i.e.
```
{
...
  "objlib": "&OBJLIB"
}
```
If you set the lib1 environment variable to BOBBUILD for example, then things will be built into the BOBBUILD library.
In this way you can configure a different library for each developer.

**Comment by pabloto** [comment]
I try to study how to configure it on my project. 
If in the same project I have to compile one source in a specific library, and another in other library. How can I configure it? Many thanks,

**Comment by pabloto** [comment]
Hi,

**Comment by edmundreinhardt** [comment]
> I try to study how to configure it on my project. If in the same project I have to compile one source in a specific library, and another in other library. How can I configure it? Many thanks,

If you want to compile two different source into two different libraries during the same build, have the 2 source in 2 different libraries.  Each library has .ibmi.json file will specifies the tgtlib (target library) 
see https://ibm.github.io/ibmi-bob/#/prepare-the-project/ibmi-json

**Comment by edmundreinhardt** [comment]
> Hi, another question about dependencies, image I have a simple db2 table and a program, looking at your example I don't understand correctly the concept of dependencies. My wish is that:
> 
> 1. If I make a change to my table (add or remove column for example), after than I make the change with create or replace table it recompile my program that have define this table.
> 2. If I make some change to my program but I the file level of my table is still the same I don't have to create or replace my table.
> 
> Which is the correct syntax of Rules.mk to make this?
> 
> Have it sense for you?
> 
> Many thanks

very simple
Assuming your database is defined by  SQL  (otherwise source is MYDB.PF or .LF)
-----
`MYDB.FILE: mydb.table
MYPGM.PGM: mypgm.rpgle MYDB.FILE`
